[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Doug Chimento <dchimento@gmail.com>"]
repository = "https://github.com/dougEfish/walletconnect-signer"
license = "MIT"

[workspace]
resolver = "2"
members = [
    "sessions",
]

[workspace.lints.rust]
unsafe_code = "forbid"
unused = "allow"
unused_variables = "allow"
unused_imports = "allow"
dead_code = "allow"

[workspace.lints.clippy]
enum_glob_use = "deny"
pedantic = "deny"
nursery = "deny"
unwrap_used = "deny"
module_name_repetitions = "allow"
#dead_code = "allow"

[workspace.dependencies]
aead = { version = "0.5.2" }
alloy-chains = {version = "0.1"}
base58 = "0.2"
base64 = "0.21"
#base64-url = "2.0"
chacha20poly1305 = "0.10"
#chrono = "0.4"
data-encoding = { version = "2"}
derive_more = {version = "0.99"}
hkdf = "0.12"
lazy_static = "1.4"
microxdg = { version = "0.1"}
once_cell = "1.16"
paste = "1.0"
rand = "0.8"
regex = "1.10"
sha2 = "0.10"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1" }
trait-variant = "0.1.2"
url = "2.4"
xtra = { version = "0.6.0", features = ["macros", "tokio"]}





