[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Doug Chimento <dchimento@gmail.com>"]
repository = "https://github.com/dougEfish/walletconnect-signer"
license = "MIT"

[workspace]
resolver = "2"
members = [ "namespaces", "relay",
    "sessions", "solana",
]
#unused_variables = "warn"
#unused_imports = "deny"

[workspace.lints.rust]
unsafe_code = "forbid"
unused_variables = "allow"
unused_imports = "allow"
dead_code = "warn"
missing_docs = "allow"

[workspace.lints.clippy]
enum_glob_use = "deny"
pedantic =  { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
module_name_repetitions = "allow"
missing_errors_doc = "allow"
must_use_candidate = "allow"
doc_markdown = "allow"
#dead_code = "allow"

[workspace.dependencies]
aead = { version = "0.5.2" }
alloy-chains = {version = "0.1", features = ["serde"]}
base58 = "0.2"
base64 = "0.22"
#base64-url = "2.0"
chacha20poly1305 = "0.10"
#chrono = "0.4"
dashmap = {version = "5"}
data-encoding = { version = "2"}
derive_more = {version = "1", features = ["full"]}
futures-util = { version = "0.3" }
hkdf = "0.12"
lazy_static = "1.4"
microxdg = { version = "0.1"}
once_cell = "1.16"
paste = "1.0"
pin-project-lite = {version = "0.2.14" }
rand = "0.8"
regex = "1.10"
sha2 = "0.10"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_with = { version = "3" }
thiserror = "1.0"
tokio = { version = "1", features = ["rt", "time", "sync", "macros", "rt-multi-thread"] }
tracing = { version = "0.1" }
trait-variant = "0.1.2"
url = "2.4"
xtra = { version = "0.6.0", features = ["macros", "tokio"]}





