[package]
name = "monedero-mesh"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true


[features]
default = ["kv", "relay"]
relay = ["monedero-relay"] # with default features
kv = ["dep:kvx"]
mock = [
    "monedero-relay/mock"
]
wasm = [
    "wasm-bindgen",
    "web-sys",
    "getrandom",
]

[dependencies]
aead = { workspace = true }
alloy-chains = {workspace = true}
async-trait = { version = "0.1.81"}
backoff = {version = "0.4.0", features = ["tokio"]} ## wasm support
base64 = { workspace = true }
#base64-url = { workspace = true }
chacha20poly1305 = { workspace = true }
chrono = { version = "0.4", default-features = false, features = [
    "std",
    "clock",
    "serde"
] }
data-encoding = { workspace = true }
derive_more = { workspace = true }
hkdf = { workspace = true }
kvx = { version = "0.9", optional = true }
lazy_static = { workspace = true }
microxdg = { workspace = true }
monedero-domain = { path = "../domain" }
monedero-cipher = { path = "../cipher" }
monedero-store = { path = "../store" }
monedero-relay = { path = "../relay", optional = true }
once_cell = { workspace = true }
paste = { workspace = true }
pin-project-lite = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
sha2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = {workspace = true}
tracing = { workspace = true}
trait-variant = {workspace = true}
url = { workspace = true }
dashmap = {  workspace = true }
x25519-dalek = { version = "2", features = ["static_secrets", "serde"] }
xtra = {workspace = true, features = ["macros", "tokio", "instrumentation"]}

## wasm
wasm-bindgen = { version = "0.2", optional = true}
web-sys = { version = "0.3", optional = true}
getrandom = { version = "0.2", features = ["js"], optional = true}
gloo-storage = { version = "0.3", optional = true}
#

[[test]]
name = "manager"
required-features = ["mock"]

[[test]]
name = "dapp"
required-features = ["mock"]

[[example]]
name = "dapp"
path = "examples/dapp/main.rs"

[dev-dependencies]
assert_matches = { version = "1.5.0" }
hex-literal = { version = "0.4.1" }
# Serialization/Deserealization changes order of fields. Preserving order
# makes it easier to construct the unittests.
serde_json = { version = "1.0", features = ["preserve_order"] }
anyhow = "1"
clap = { version = "4.4", features = ["derive"] }
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
env_logger = { version = "0.9.3" }
tracing = { version = "0.1" }
tracing-error = { version = "0.2.0"}
dotenvy = {version = "0.15"}
tracing-subscriber = { version = "0.3", features = ["env-filter", "serde"] }
ratatui = { version = "0.28", features = ["all-widgets"]}
tui-input = "0.10.0"

